_wandb:
    value:
        cli_version: 0.22.3
        e:
            6hydo88ixs1y5a5b6k1vdbz7yi3v8gr8:
                apple:
                    ecpuCores: 6
                    gpuCores: 10
                    memoryGb: 32
                    name: Apple M4
                    pcpuCores: 4
                    ramTotalBytes: "34359738368"
                    swapTotalBytes: "5368709120"
                args:
                    - --layer_mode
                    - all
                    - --wandb_run_name
                    - layer-all_1e-4_1e-3_iou_loss0.3
                    - --lr
                    - "1e-4"
                    - --weight_decay
                    - "1e-3"
                    - --data_split_mode
                    - scene_disjoint
                    - --batch_size
                    - "128"
                    - --use_iou_loss
                    - --iou_lambda
                    - "0.3"
                codePath: train/vggt_train.py
                codePathLocal: train/vggt_train.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "994662584320"
                        used: "626170818560"
                email: filippo.ziliotto@studenti.unipd.it
                executable: /Library/anaconda3/envs/covision/bin/python
                git:
                    commit: 9cfe16191fb02c8f5b80201ee43c747cf2aeca29
                    remote: https://github.com/ai4ce/CoVISION.git
                host: Mac.homenet.telecomitalia.it
                memory:
                    total: "34359738368"
                os: macOS-15.6.1-arm64-arm-64bit
                program: /Users/filippoziliotto/Desktop/Repos/CoVISION/train/vggt_train.py
                python: CPython 3.9.24
                root: /Users/filippoziliotto/Desktop/Repos/CoVISION
                startedAt: "2025-11-09T22:20:15.790887Z"
                writerId: 6hydo88ixs1y5a5b6k1vdbz7yi3v8gr8
        m: []
        python_version: 3.9.24
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 13
                - 16
                - 61
            "4": 3.9.24
            "5": 0.22.3
            "12": 0.22.3
            "13": darwin-arm64
aug_swap_prob:
    value: 0.5
batch_size:
    value: 128
data_split_mode:
    value: scene_disjoint
device:
    value: mps
epochs:
    value: 50
es_min_delta:
    value: 0.0001
es_patience:
    value: 5
iou_lambda:
    value: 0.3
layer_mode:
    value: all
lr:
    value: 0.0001
lr_factor:
    value: 0.5
lr_patience:
    value: 3
max_grad_norm:
    value: 0
max_neg_ratio:
    value: 1
optimizer:
    value: adamw
out_dir:
    value: train/classifier
rank_lambda:
    value: 0.1
rank_margin:
    value: 0.1
rank_num_samples:
    value: 1024
reg_lambda:
    value: 0.3
seed:
    value: 2026
use_iou_loss:
    value: true
use_rank_loss:
    value: false
use_reg_loss:
    value: false
wandb_off:
    value: false
wandb_project:
    value: Co-Vision
wandb_run_name:
    value: layer-all_1e-4_1e-3_iou_loss0.3
weight_decay:
    value: 0.001
zero_shot:
    value: false
